# Generated by Django 3.2.7 on 2021-09-14 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='is_archived',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Archived'),
        ),
        migrations.AlterField(
            model_name='note',
            name='text',
            field=models.TextField(max_length=1000, verbose_name='Text'),
        ),
        migrations.AlterModelTable(
            name='note',
            table='notes',
        ),
        migrations.AlterModelTable(
            name='notetag',
            table='note_tags',
        ),
        migrations.AlterModelTable(
            name='tag',
            table='tags',
        ),
        migrations.CreateModel(
            name='SharedNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_viewed', models.BooleanField(blank=True, default=False, null=True, verbose_name='Viewed')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_note', to='notes.note', verbose_name='Note')),
                ('shared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='note_shared_by', to=settings.AUTH_USER_MODEL, verbose_name='Shared by')),
                ('shared_with', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='note_shared_with', to=settings.AUTH_USER_MODEL, verbose_name='Shared with')),
            ],
            options={
                'db_table': 'shared_notes',
            },
        ),
    ]
