# Generated by Django 3.2.7 on 2021-09-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20210914_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='text',
            field=models.TextField(verbose_name='Text'),
        ),
    ]
